apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-test
  namespace: argocd
spec:
  destination:
    namespace: vault-test
    server: 'https://kubernetes.default.svc'
  source:
    path: testchart
    repoURL: 'https://github.com/triadcode/argovault.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true