apiVersion: v1
metadata:
  name: {{ include "test.fullname" . }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "dev/customers/test"
data:
  DB_PASS: <POSTGRES_PASSWORD>
  DB_USER: <POSTGRESQL_USERNAME>
kind: Secret

type: Opaque
